package com.orion.user_management.authentication.security;

import org.springframework.security.web.authentication.SavedRequestAwareAuthenticationSuccessHandler;

public class OrionLoginSuccessService extends SavedRequestAwareAuthenticationSuccessHandler
{
}